### PR TITLE
Support cREAL

### LINKED ISSUE #6: Update to UCK 2.1.0
Bump to UCK 2.1.0 to support cREAL

### LINKED ISSUE #7: Add support for cREAL
Add cREAL as an asset and add the exchange to support cREAL minting and burning

### PR DESCRIPTION
**Pull request by kyscott18**
Allows for the minting and burning of cREAL, the newest asset added to Celo's Mento exchange. 

This was accomplished by first upgrading the `@celo-tools/use-contractkit` package to the latest version which supports `cREAL` as a `StableToken`. Next, cREAL was added to the token list in the interface and the correct exchange was linked to that token. Confirmed proper function with https://explorer.celo.org/tx/0x5a32f26c29d21602291607f32ac90af25857f910aca2263fb591c3f652fdce3e/token-transfers and https://explorer.celo.org/tx/0x59c3f06fad88d6d657d5f1318d63f2e3188be0f0e8cb53907a9a5a1646486440/token-transfers 

Closes #6 and closes #7

### CODE REVIEW

**Comment by jmrossy** [comment]
@kyscott18 Thanks for the PR!

I wish you had messaged me first because I could have told you that I already have these changes in a local branch but there's a problem with use-ck v2.1.0. That's why the Vercel deployment failed in CI here. I'm waiting for the v2.1.1 with the WalletConnect build fix and then I'll ship an update.

Nonetheless, thanks for taking the time!!

**Comment by kyscott18** [comment]
No problem. I wasn't sure who was in charge of the repo so I didn't know who to message. I just did it really quick as I was adding cREAL to the Mobius Mento interface. I have gotten use-ck v2.1.0 to build in two different repos with https://github.com/mobiusAMM/mobius-interface/blob/staging/package.json and https://github.com/Dahlia-Finance/pinnata-interface/blob/master/package.json so maybe that could help

**Comment by kyscott18** [comment]
@jmrossy I think you are right about walletconnect, even it you can get it to build, there are some issues with valora

**Comment by jmrossy** [comment]
Thanks again for the PR! Closing as this is superseded by #9

**Pull request closed without merging**
